<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="HappyStudio.Mvvm.Input.Wpf" Version="1.0.1" />
    <PackageReference Include="H.NotifyIcon.Wpf" Version="2.3.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.0" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Views\" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="AssemblyInfo.cs">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Page Update="Views\MainWindow.xaml">
      <SubType>Designer</SubType>
    </Page>
  </ItemGroup>

</Project>
